# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Machac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  pod 'RealmSwift', '~> 2.10.0'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'Swinject'
  pod 'RxSwift'
  pod 'R.swift'

end
